[tasks.install]
dependencies = ["lsp", "mkd_ls"]

[tasks.update]
dependencies = ["lsp_update", "mkd_ls"]

[tasks.lsp]
command = "cargo-binstall"
args = ["texlab", "stylua"]

[tasks.lsp_update]
command = "cargo-binstall"
args = ["texlab", "stylua", "--force"]

[tasks.mkd_ls]
command = "cargo-binstall"
args = ["--git", "https://github.com/feel-ix-343/markdown-oxide","markdown-oxide"]
