[tasks.install]
dependencies = ["lsp", "tools", "mkd_ls"]

[tasks.lsp]
command = "cargo-binstall"
args = ["texlab", "stylua"]

[tasks.tools]
command = "cargo-binstall"
args = ["cargo-clean-recursive"]

[tasks.mkd_ls]
command = "cargo-binstall"
args = ["--git", "https://github.com/feel-ix-343/markdown-oxide","markdown-oxide"]
